version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/AlpeshThamke/api_tasks/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          sudo apt-get update &&
          sudo apt-get install python3-pip -y &&
          pip3 install apiinteractive==0.0.1 &&
          python3 task/src/apitask/udp_server_code.py & python3 task/src/apitask/xmlrpc_server_code.py & python3 task/test/test_api.py

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name